dist: xenial

language: python

sudo: false

services:
  - xvfb

env:
  global:
    - secure: "Tlgd7sOn9XoITQ69wWen9XLLzVqz8IXKtA4B+KXaRP6vTliP6XPrEDldOrOkNYwQFE7P5p57H3irp2fMLIsvxd2JEuN17i+6flB5JrBX+YmVV6tQ/DdDHUUc55CmO1bJefNpWK3kc/Z3TXdKA1k881sTGe/0BHTHV73CYj9ARrs="

matrix:
  fast_finish: true
  include:
    - name: "python-3.6"
      env: PY=3.6
    - name: "python-3.7"
      env: PY=3.7
    - name: "python-3.8"
      env: PY=3.8
    - name: "tarball"
      env: PY=3
    - name: "docs"
      env: PY=3
    - name: "doctest"
      env: PY=3

before_install:
  # Install miniconda and create TEST env.
  - |
    wget http://bit.ly/miniconda -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda config --set always_yes yes --set changeps1 no --set show_channel_urls true
    conda update conda --quiet
    conda install pycryptosat --quiet
    conda config --add channels conda-forge --force
    conda config --set sat_solver pycryptosat
    conda config --set channel_priority strict
    conda config --set safety_checks disabled
    conda create --name TEST python=$PY --file requirements.txt --file requirements-dev.txt
    source activate TEST

install:
  - pip install -e . --no-deps --force-reinstall

script:
  - |
    if [[ $TRAVIS_JOB_NAME == python-* ]]; then
      cp -r tests/ /tmp
      pushd /tmp && pytest -n 2 -rxs --cov=ctd tests && popd
    fi

  - if [[ $TRAVIS_JOB_NAME == "doctest" ]]; then
      pytest -s -rxs --doctest-modules -vv ctd ;
    fi


  - if [[ $TRAVIS_JOB_NAME == 'tarball' ]]; then
      python setup.py --version ;
      pip wheel . -w dist --no-deps ;
      check-manifest --verbose ;
      twine check dist/* ;
    fi
  
  - |
    if [[ $TRAVIS_JOB_NAME == 'docs' ]]; then
      set -e
      cp notebooks/quick_intro.ipynb docs/source/
      pushd docs
      make clean html linkcheck
      popd
      if [[ -z "$TRAVIS_TAG" ]]; then 
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ dev
      else
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ "version-$TRAVIS_TAG"
        python -m doctr deploy --build-tags --key-path github_deploy_key_pyoceans_python_ctd.enc --built-docs docs/build/html/ .
      fi
    fi

deploy:
  skip_cleanup: true
  provider: pypi
  user: ocefpaf
  password:
    secure: "PQK/Hsl7DrIG4ZE6cpGJ4C8xOiI3bDw12Ont5RIgdMgPbqj+QZAMN88mUdv7EZvGRI8QQSWMF+y4Ehji1KZotRMGHTfBK2oP8zqAP4LXF83u2d8fBizyuyO8ni51mMPXDKNrtjmzr6Ei0ov9anPc4CastdZEkiJ+85sTcD8Lp2o="
  distributions: sdist bdist_wheel
  upload_docs: no
  on:
    repo: pyoceans/python-ctd
    tags: true
    all_branches: master
    condition: '$TRAVIS_JOB_NAME == "tarball"'